package main

import (
	"fmt"

	"github.com/equinox-io/equinox"
)

// assigned when creating a new application in the dashboard
const appID = "app_96H5xG6nZm1" /* set app id */

// public portion of signing key generated by `equinox genkey`
/* your public key */
var publicKey = []byte(`	
-----BEGIN ECDSA PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEdOROI+hOlTvEdCAIek1Shrqw03dQBOPB
yGjR+yge9ymy46zZFgyS3yXoPi1ekrH4QxMSrk+0n38fPwCJK9FmGYaZ6X6ciEmX
PZm0cxkFGRSGbTUj9lwuQrHZy4ni3trS
-----END ECDSA PUBLIC KEY-----
`)

func equinoxUpdate() error {
	var opts equinox.Options
	if err := opts.SetPublicKeyPEM(publicKey); err != nil {
		return err
	}

	// check for the update
	resp, err := equinox.Check(appID, opts)
	switch {
	case err == equinox.NotAvailableErr:
		fmt.Println("No update available, already at the latest version!")
		return nil
	case err != nil:
		fmt.Println("Update failed:", err)
		return err
	}

	// fetch the update and apply it
	err = resp.Apply()
	if err != nil {
		return err
	}

	fmt.Printf("Updated to new version: %s!\n", resp.ReleaseVersion)
	return nil
}
